spring:
  application:
    name: cine-book

  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Redis Configuration
  cache:
    type: redis
    redis:
      time-to-live: 60000         # mỗi cache sống 60 giây
      cache-null-values: false    # không cache giá trị null
      use-key-prefix: true        # sử dụng tiền tố cho các key trong cache
      key-prefix: "cine-book"     # tiền tố cho các key trong cache

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 10000              # timeout kết nối tối đa 60 giây

  # Server Configuration
  server:
    port: 8080

  # Swagger
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    #    tags-sorter: alpha            # Sắp xếp theo bảng chữ cái alphabetical
    #    operations-sorter: alpha      # Sắp xếp API methods (GET, POST, PUT, DELETE) theo tên (alphabet).
    api-docs:
      path: /v3/api-docs             # Đây là endpoint cung cấp JSON OpenAPI cho Swagger UI.

    # JWT Configuration
    jwt:
      secret: ${JWT_SECRET}
      expirationMs: ${JWT_EXPIRATION_MS:24h}
